### PR TITLE
1 notes create + edit + delete

### PR DESCRIPTION
**Pull request by Kate-Kn**

### CODE REVIEW

**Review by dhanyajagan — APPROVED** [review]
I think functionality looks great! I think it is ok to push the changes. Also, does it adhere to clean architecture/SOLID? We may need to make a few refactoring changes here and there, but that can be done later, I think

**Review by mudrakat — APPROVED** [review]

**Comment by calicac001** [comment]
Everything looks great functionally! I also just think that you can just clean up your code so it adheres more to clean architecture. Also, maybe update the UI a bit.

**Review by dhanyajagan — APPROVED** [review]

**Comment by Kate-Kn** [comment]
I worked on creation, editing and deletion of notes. This is core functionality for Notes part of the application. I tried to do all the changes ASAP as a lot of US are dependent on this (for example, search, pin, labeling). In my code structure, I have entity, use case, presenter and gateway levels. 
I plan to add a Controller level, so that it adheres more to Clean Architecture. Also I will add some automated unit tests, so that I don't have to test all the functionality manually during every small change. I intend to make the UI more convenient as well.

**Comment by dhanyajagan** [comment]
This Pull Request is very important because it allows for the creation, deletion, and editing of notes- which is a major part of the functionality of our application. The basic functionality of this feature works just as intended, with the user being able to create notes, delete them and edit them, with proper form of data persistence that saves the notes (in SQLDatabase).
In regards to areas of improvement for this current feature implementation, unit tests need to be implemented, and might need to have minimal refactoring to adhere to clean architecture layers. There doesn’t seem to be any violations of the SOLID design principles, however, it would be helpful to make sure that these design principles are still adhered to after refactoring. Also, after making these changes, if time persists, the UI can be updated a little bit to enhance the overall appearance of the app.

**Pull request merged**
